// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/minimesh.proto

package minimeshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // base64 WireGuard public key
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_minimesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverlayIp     string                 `protobuf:"bytes,1,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"` // e.g. 10.99.0.1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_minimesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_proto_minimesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type Peer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OverlayIp     string                 `protobuf:"bytes,3,opt,name=overlay_ip,json=overlayIp,proto3" json:"overlay_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_minimesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{3}
}

func (x *Peer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Peer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Peer) GetOverlayIp() string {
	if x != nil {
		return x.OverlayIp
	}
	return ""
}

type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*Peer                `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_proto_minimesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{4}
}

func (x *PeerList) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"` // set by the coordinator from the sender's stream identity
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // opaque; peers put a marshalled Candidates here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_minimesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{5}
}

func (x *Envelope) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Envelope) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Candidates is the Envelope payload peers exchange. The coordinator never
// decodes it. NetBird encrypts this end to end; minimesh does not (yet).
type Candidates struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Candidates []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// reply_requested asks the receiver to answer with its own candidates, in
	// case its earlier envelope was sent before our Signal stream existed.
	ReplyRequested bool `protobuf:"varint,2,opt,name=reply_requested,json=replyRequested,proto3" json:"reply_requested,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Candidates) Reset() {
	*x = Candidates{}
	mi := &file_proto_minimesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidates) ProtoMessage() {}

func (x *Candidates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidates.ProtoReflect.Descriptor instead.
func (*Candidates) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{6}
}

func (x *Candidates) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *Candidates) GetReplyRequested() bool {
	if x != nil {
		return x.ReplyRequested
	}
	return false
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "host" or "srflx" (ICE vocabulary, RFC 8445 5.1.1)
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // ip:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_proto_minimesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_minimesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_proto_minimesh_proto_rawDescGZIP(), []int{7}
}

func (x *Candidate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Candidate) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_proto_minimesh_proto protoreflect.FileDescriptor

const file_proto_minimesh_proto_rawDesc = "" +
	"\n" +
	"\x14proto/minimesh.proto\x12\bminimesh\"D\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x01 \x01(\tR\toverlayIp\",\n" +
	"\vSyncRequest\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\"X\n" +
	"\x04Peer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"overlay_ip\x18\x03 \x01(\tR\toverlayIp\"0\n" +
	"\bPeerList\x12$\n" +
	"\x05peers\x18\x01 \x03(\v2\x0e.minimesh.PeerR\x05peers\"H\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"j\n" +
	"\n" +
	"Candidates\x123\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x13.minimesh.CandidateR\n" +
	"candidates\x12'\n" +
	"\x0freply_requested\x18\x02 \x01(\bR\x0ereplyRequested\"3\n" +
	"\tCandidate\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr2\xbb\x01\n" +
	"\vCoordinator\x12A\n" +
	"\bRegister\x12\x19.minimesh.RegisterRequest\x1a\x1a.minimesh.RegisterResponse\x123\n" +
	"\x04Sync\x12\x15.minimesh.SyncRequest\x1a\x12.minimesh.PeerList0\x01\x124\n" +
	"\x06Signal\x12\x12.minimesh.Envelope\x1a\x12.minimesh.Envelope(\x010\x01B2Z0github.com/aamirlatif1/minimesh/proto;minimeshpbb\x06proto3"

var (
	file_proto_minimesh_proto_rawDescOnce sync.Once
	file_proto_minimesh_proto_rawDescData []byte
)

func file_proto_minimesh_proto_rawDescGZIP() []byte {
	file_proto_minimesh_proto_rawDescOnce.Do(func() {
		file_proto_minimesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_minimesh_proto_rawDesc), len(file_proto_minimesh_proto_rawDesc)))
	})
	return file_proto_minimesh_proto_rawDescData
}

var file_proto_minimesh_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_minimesh_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: minimesh.RegisterRequest
	(*RegisterResponse)(nil), // 1: minimesh.RegisterResponse
	(*SyncRequest)(nil),      // 2: minimesh.SyncRequest
	(*Peer)(nil),             // 3: minimesh.Peer
	(*PeerList)(nil),         // 4: minimesh.PeerList
	(*Envelope)(nil),         // 5: minimesh.Envelope
	(*Candidates)(nil),       // 6: minimesh.Candidates
	(*Candidate)(nil),        // 7: minimesh.Candidate
}
var file_proto_minimesh_proto_depIdxs = []int32{
	3, // 0: minimesh.PeerList.peers:type_name -> minimesh.Peer
	7, // 1: minimesh.Candidates.candidates:type_name -> minimesh.Candidate
	0, // 2: minimesh.Coordinator.Register:input_type -> minimesh.RegisterRequest
	2, // 3: minimesh.Coordinator.Sync:input_type -> minimesh.SyncRequest
	5, // 4: minimesh.Coordinator.Signal:input_type -> minimesh.Envelope
	1, // 5: minimesh.Coordinator.Register:output_type -> minimesh.RegisterResponse
	4, // 6: minimesh.Coordinator.Sync:output_type -> minimesh.PeerList
	5, // 7: minimesh.Coordinator.Signal:output_type -> minimesh.Envelope
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_minimesh_proto_init() }
func file_proto_minimesh_proto_init() {
	if File_proto_minimesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_minimesh_proto_rawDesc), len(file_proto_minimesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_minimesh_proto_goTypes,
		DependencyIndexes: file_proto_minimesh_proto_depIdxs,
		MessageInfos:      file_proto_minimesh_proto_msgTypes,
	}.Build()
	File_proto_minimesh_proto = out.File
	file_proto_minimesh_proto_goTypes = nil
	file_proto_minimesh_proto_depIdxs = nil
}
